// Tests for scripts/ops/render-mainnet-backend-env.mjs — the mainnet env-template
// generator. These pin the delta transform so a future edit can't silently ship a
// mainnet template that (a) points at a testnet RPC/chainId, (b) keeps the retired
// HMAC / arbitrator key, (c) drops the SHARE_URL_SECRET, or (d) hardcodes a
// per-deploy address instead of a TODO(operator) placeholder.

import { test } from "node:test";
import assert from "node:assert/strict";

import {
  MAINNET_RPC,
  MAINNET_CHAIN_ID,
  repointOpRef,
  transformLine,
  transformTemplate,
  collectOpRefs,
  buildInventoryBlock,
  spliceInventory,
  generateAll,
} from "./render-mainnet-backend-env.mjs";

// --- repointOpRef ---------------------------------------------------------

test("repointOpRef: prod-* vault → mainnet-*, and -testnet item slug → -mainnet", () => {
  assert.equal(
    repointOpRef("op://prod-backend/aws-signer-testnet/kms-key-id"),
    "op://mainnet-backend/aws-signer-testnet/kms-key-id".replace("testnet", "mainnet")
  );
  assert.equal(
    repointOpRef("op://prod-backend-external/resend-api-key/password"),
    "op://mainnet-backend-external/resend-api-key/password"
  );
  assert.equal(repointOpRef("op://prod-indexer/database-url/password"), "op://mainnet-indexer/database-url/password");
});

test("repointOpRef: preserves a multi-word field segment", () => {
  assert.equal(
    repointOpRef("op://prod-backend/admin-eoa-arbitrator-testnet/private key"),
    "op://mainnet-backend/admin-eoa-arbitrator-mainnet/private key"
  );
});

test("repointOpRef: leaves a non-op value untouched", () => {
  assert.equal(repointOpRef("redis://redis:6379"), "redis://redis:6379");
});

// --- transformLine --------------------------------------------------------

test("transformLine: identity literals flip to mainnet", () => {
  assert.equal(transformLine("AUTH_CHAIN_ID=420420417"), `AUTH_CHAIN_ID=${MAINNET_CHAIN_ID}`);
  assert.equal(transformLine("RPC_URL=https://eth-rpc-testnet.polkadot.io/"), `RPC_URL=${MAINNET_RPC}`);
  assert.equal(transformLine("USDC_LIQUIDITY_CHAIN=testnet"), "USDC_LIQUIDITY_CHAIN=mainnet");
  assert.equal(transformLine("INGESTION_PREFUND_ENABLED=true"), "INGESTION_PREFUND_ENABLED=false");
  assert.equal(transformLine("REDIS_URL=redis://redis:6379"), "REDIS_URL=redis://mainnet-redis:6379");
  assert.equal(transformLine("REDIS_NAMESPACE=agent-platform"), "REDIS_NAMESPACE=agent-platform-mainnet");
  assert.equal(
    transformLine("INDEXER_STATUS_URL=http://indexer:42069/status"),
    "INDEXER_STATUS_URL=http://mainnet-indexer:42069/status"
  );
});

test("transformLine: removed keys are dropped (returns a non-string)", () => {
  assert.notEqual(typeof transformLine("AUTH_JWT_SECRETS=op://prod-backend/auth-jwt-secrets/password"), "string");
  assert.notEqual(typeof transformLine("ARBITRATOR_SIGNER_PRIVATE_KEY=op://prod-backend/x/private key"), "string");
});

test("transformLine: per-deploy unknowns become commented TODO(operator)", () => {
  assert.match(transformLine("TREASURY_POLICY_ADDRESS=0xabc"), /^# TREASURY_POLICY_ADDRESS=\s+TODO\(operator\):/u);
  const admin = transformLine("AUTH_ADMIN_WALLETS=0x6778F050eAc8313e4dbB176d7BAB44510E833ac8");
  assert.match(admin, /^# AUTH_ADMIN_WALLETS=/u);
  assert.match(admin, /NEVER the testnet hot key nor the leaked 0xFd2E/u);
});

test("transformLine: op:// values are repointed; kept keys stay literal", () => {
  assert.equal(
    transformLine("METRICS_BEARER_TOKEN=op://prod-backend/metrics-bearer-token/password"),
    "METRICS_BEARER_TOKEN=op://mainnet-backend/metrics-bearer-token/password"
  );
  assert.equal(transformLine("SIGNER_BACKEND=kms"), "SIGNER_BACKEND=kms");
  assert.equal(transformLine("JWT_BACKEND=kms"), "JWT_BACKEND=kms");
  // the USDC precompile is the one correct cross-env reuse — unchanged
  assert.equal(
    transformLine("TOKEN_ADDRESS=0x0000053900000000000000000000000001200000"),
    "TOKEN_ADDRESS=0x0000053900000000000000000000000001200000"
  );
});

test("transformLine: the ponder RPC key carries the chain id and is renamed", () => {
  assert.equal(
    transformLine("PONDER_RPC_URL_420420417=https://eth-rpc-testnet.polkadot.io/"),
    `PONDER_RPC_URL_420420419=${MAINNET_RPC}`
  );
});

test("transformLine: comments and blanks pass through verbatim", () => {
  assert.equal(transformLine("# a comment"), "# a comment");
  assert.equal(transformLine(""), "");
});

// --- transformTemplate ----------------------------------------------------

test("transformTemplate: removes HMAC, adds SHARE_URL_SECRET, flips chain id", () => {
  const src = [
    "AUTH_CHAIN_ID=420420417",
    "AUTH_JWT_SECRETS=op://prod-backend/auth-jwt-secrets/password",
    "KMS_KEY_ID=op://prod-backend/aws-signer-testnet/kms-key-id",
  ].join("\n");
  const out = transformTemplate(src, "deploy/backend.env.template", {
    additions: ["SHARE_URL_SECRET=op://mainnet-backend/share-url-secret/password"],
  });
  assert.match(out, /GENERATED by scripts\/ops\/render-mainnet-backend-env\.mjs/u);
  assert.match(out, /AUTH_CHAIN_ID=420420419/u);
  assert.ok(!/^AUTH_JWT_SECRETS=/mu.test(out), "HMAC key removed");
  assert.match(out, /^KMS_KEY_ID=op:\/\/mainnet-backend\/aws-signer-mainnet\/kms-key-id$/mu);
  assert.match(out, /^SHARE_URL_SECRET=op:\/\/mainnet-backend\/share-url-secret\/password$/mu);
});

// --- inventory block ------------------------------------------------------

test("collectOpRefs + buildInventoryBlock: one parseable row per op:// ref", () => {
  const refs = collectOpRefs("A=op://mainnet-backend/i/f\nB=literal\nC=op://mainnet-indexer/db/password\n");
  assert.deepEqual(refs.map((r) => r.varName), ["A", "C"]);
  const block = buildInventoryBlock(refs);
  // rows must match the lint's row parser: | `VAR` | `op://...` |
  assert.match(block, /\|\s*`A`\s*\|\s*`op:\/\/mainnet-backend\/i\/f`/u);
  assert.match(block, /\|\s*`C`\s*\|\s*`op:\/\/mainnet-indexer\/db\/password`/u);
});

test("spliceInventory: replaces the marked block idempotently", () => {
  const base = "# doc\n\n<!-- BEGIN mainnet-generated (render-mainnet-backend-env.mjs) — do not hand-edit -->\nOLD\n<!-- END mainnet-generated -->\n";
  const block = buildInventoryBlock([{ varName: "X", path: "op://mainnet-backend/x/f" }]);
  const once = spliceInventory(base, block);
  assert.ok(!once.includes("OLD"), "old block replaced");
  assert.match(once, /`X`/u);
  assert.equal(spliceInventory(once, block), once, "second splice is a no-op");
});

test("spliceInventory: appends the block when markers are absent", () => {
  const out = spliceInventory("# doc, no markers\n", buildInventoryBlock([{ varName: "X", path: "op://mainnet-backend/x/f" }]));
  assert.match(out, /BEGIN mainnet-generated/u);
  assert.match(out, /`X`/u);
});

// --- end-to-end against the real committed testnet templates ---------------

test("generateAll: the real transform yields the mainnet essentials", () => {
  const files = generateAll();
  const backend = files["deploy/backend.mainnet.env.template"];
  assert.match(backend, /AUTH_CHAIN_ID=420420419/u);
  assert.match(backend, /RPC_URL=https:\/\/eth-rpc\.polkadot\.io\//u);
  assert.match(backend, /^SHARE_URL_SECRET=op:\/\/mainnet-backend\/share-url-secret\/password$/mu);
  assert.ok(!/^AUTH_JWT_SECRETS=/mu.test(backend), "no HMAC key");
  assert.ok(!/^ARBITRATOR_SIGNER_PRIVATE_KEY=/mu.test(backend), "no arbitrator key");
  assert.ok(!/op:\/\/prod-/u.test(backend), "no prod-* vault refs leak into mainnet");
  assert.match(backend, /^REDIS_URL=redis:\/\/mainnet-redis:6379$/mu);
  assert.match(backend, /^REDIS_NAMESPACE=agent-platform-mainnet$/mu);
  assert.match(backend, /^INDEXER_STATUS_URL=http:\/\/mainnet-indexer:42069\/status$/mu);
  // no testnet RPC anywhere in the rendered mainnet templates
  assert.ok(!files["deploy/indexer.mainnet.env.template"].includes("eth-rpc-testnet.polkadot.io"));
});
