#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${1:-mcp-server/.env.local}"

DWELLER_RPC_URL_VALUE="${DWELLER_RPC_URL:-}"
POLKADOT_RPC_URL_VALUE="${POLKADOT_RPC_URL:-}"
RPC_URL_VALUE="${RPC_URL:-${POLKADOT_RPC_URL_VALUE:-${DWELLER_RPC_URL_VALUE:-http://127.0.0.1:8545}}}"
SIGNER_KEY_VALUE="${SIGNER_PRIVATE_KEY:-${PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}}"
TOKEN_ADDRESS_VALUE="${MOCK_DOT_ADDRESS:-${TOKEN_ADDRESS:-}}"

required_vars=(
  TREASURY_POLICY_ADDRESS
  AGENT_ACCOUNT_ADDRESS
  ESCROW_CORE_ADDRESS
  REPUTATION_SBT_ADDRESS
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "Missing required environment variable: $var_name" >&2
    exit 1
  fi
done

if [[ -z "$TOKEN_ADDRESS_VALUE" ]]; then
  echo "Missing required environment variable: MOCK_DOT_ADDRESS or TOKEN_ADDRESS" >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
DWELLER_RPC_URL=$DWELLER_RPC_URL_VALUE
POLKADOT_RPC_URL=$POLKADOT_RPC_URL_VALUE
RPC_URL=$RPC_URL_VALUE
SIGNER_PRIVATE_KEY=$SIGNER_KEY_VALUE
TREASURY_POLICY_ADDRESS=$TREASURY_POLICY_ADDRESS
AGENT_ACCOUNT_ADDRESS=$AGENT_ACCOUNT_ADDRESS
ESCROW_CORE_ADDRESS=$ESCROW_CORE_ADDRESS
REPUTATION_SBT_ADDRESS=$REPUTATION_SBT_ADDRESS
DISCOVERY_REGISTRY_ADDRESS=${DISCOVERY_REGISTRY_ADDRESS:-}
XCM_WRAPPER_ADDRESS=${XCM_WRAPPER_ADDRESS:-}
STRATEGIES_JSON=${STRATEGIES_JSON:-[]}
SUPPORTED_ASSETS_JSON=[{"symbol":"DOT","assetClass":"custom","address":"$TOKEN_ADDRESS_VALUE","decimals":18}]
SUPPORTED_ASSETS=DOT:$TOKEN_ADDRESS_VALUE
EOF

echo "Wrote $OUTPUT_FILE"
